-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  billing_status public.subscription_status default 'free'::public.subscription_status
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security
alter table profiles
  enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- This trigger automatically creates a profile for new users.
-- See https://supabase.com/docs/guides/auth/managing-user-data#creating-a-profile-for-new-users
create function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url) 
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create posts table
create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  title text not null,
  slug text not null unique,
  content text,
  excerpt text,
  published_at timestamp with time zone,
  is_premium boolean default false not null,
  author_id uuid references public.profiles on delete set null
);

-- RLS for posts table
alter table posts enable row level security;

-- Allow public read access to published posts
create policy "Published posts are viewable by everyone." on posts
  for select using (published_at is not null and published_at <= now());

-- Allow admin users to perform any action
create policy "Admins can manage all posts." on posts
  for all using ( (select auth.uid() in (select id from profiles where billing_status = 'founder')) );

-- Create ENUM type for billing status
create type public.subscription_status as enum ('free', 'premium', 'founder');